## roles/torrentserver/Fedora.yml
## Fedora main file
# vim:ft=yaml.ansible:
---
# exists: /usr/local/bin/automatic
- name: Automatic RSS Install Status
  stat:
    path: /usr/local/bin/automatic
  register: automatic

- include_role:
    name: ansible-role-repo-rpmfusion

# packages: 
# git, automake, libcurl-devel, libxml2-devel, pcre-devel
- name: Install packages
  dnf:
    name:
      - "git"
      - "gcc"
      - "make"
      - "automake"
      - "libcurl-devel"
      - "libxml2-devel"
      - "pcre-devel"
      #- "python-firewall"
      - "transmission-cli"
      - "transmission-daemon"
      #- "transmission-remote-cli"
      - "unrar"
    state: present
  notify:
    - start transmission
    - start automatic

- name: git clone 1100101/Automatic.git
  git:
    repo: 'https://github.com/1100101/Automatic.git'
    dest: /tmp/Automatic
    clone: yes
  when: not automatic.stat.exists

- name: run autogen
  command: /tmp/Automatic/autogen.sh
  when: not automatic.stat.exists

- name: make install Automatic
  make:
    chdir: /tmp/Automatic
    target: install
  when: not automatic.stat.exists

# template: automatic.conf automatic.service > / (selinux )
- name: automatic.conf
  template:
    src: automatic.conf.j2
    dest: /etc/automatic.conf
  notify:
    - start automatic

- name: systemd services conf
  template:
    src: '{{ item }}.service.j2'
    dest: '/usr/lib/systemd/system/{{ item }}.service'
  notify:
    - daemonreload
    - start transmission
    - start automatic
  with_items:
    - transmission
    - automatic

- name: Open firewall
  firewalld:
    port: '{{ item }}'
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 9091/tcp
    - 51413/tcp

- name: stop transmission daemon
  service: name=transmission state=stopped
...
