## roles/torrentserver/tasks/main.yml
## Role main file
# vim:ft=yaml.ansible
---
- include_vars: secrets.yml

- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: stop transmission daemon
  service: name=transmission state=stopped

- name: transmission-config
  tags: transconf
  template:
    src: transmission-settings.json.j2
    dest: '{{ userHome }}/.config/transmission-daemon/settings.json'
    owner: '{{ transmissionUser }}'
    group: '{{ transmissionUser }}'
  notify:
    - start transmission

- name: sysctl buffers
  sysctl:
    name: '{{ item }}'
    value: "16777216"
    sysctl_set: yes
  with_items:
    - "net.core.rmem_max"
    - "net.core.wmem_max"

- name: Add torrent done script
  template:
    src: '{{ transmissionDoneScriptFile }}.j2'
    dest: '{{ transmissionDoneScriptPath }}/{{ transmissionDoneScriptFile }}'
    owner: '{{ transmissionUser }}'
    group: '{{ transmissionUser }}'

...
